mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from activity.dashboard import beneficiary_pie_chart

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
    path("profile/",include("userprofile.urls")),
    path("beneficiary/", include('beneficiary.urls')),
    path("activity/", include('activity.urls')),
    path('dashboard/', beneficiary_pie_chart, name='beneficiary_pie_chart'),


  
]

#for the image ..
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),

    path ("list/", views.question_list, name="question_list"),
    path ("edit/<int:question_id>/", views.edit_question, name="edit_question"),
    path("add/", views.add_question, name="add_question"),
    
    path("delete/<int:question_id>/", views.delete_question,name="delete_question"),
    
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),

    # url for csv file upload
    path("uploadcsv/", views.upload_csv, name="upload_csv"),
    # download the csv file 
    path('download/questions/', views.download_questions_csv, name='download_questions_csv'),

    # making table for the global template
    path("table/", views.global_table, name="global_table"),

    # for changing the status of the question
    path('status/<int:question_id>/', views.question_status, name='question_status'),

    # for export the data using SQL
    path('export/questions/', views.export_questions, name='export_questions'),

    # for importing the data using Sql 
    path('import/', views.ImportQuestionsView.as_view(), name='import_questions'),

    #for getting the data with SQL query and set it in the table 
    path('table/sql/', views.sql_table, name='import_questions'),

    # for AjAX 
    path('get_questions/', views.get_questions, name='get_questions'),
    # print the question in the html page 
    path('listquestions/', views.show_questions, name='show_questions_page'),



    # url for API
    path('questions/', views.QuestionList.as_view(), name='question-list'),
    path('questions/<int:pk>/', views.QuestionDetail.as_view(), name='question-detail'),
    path('choices/', views.ChoiceList.as_view(), name='choice-list'),
    path('choices/<int:pk>/', views.ChoiceDetail.as_view(), name='choice-detail'),

]

polls/models.py
import datetime
from django.contrib import admin
from django.db import models
from django.utils import timezone
import csv
from django.http import HttpResponse

class Question(models.Model):
    ACTIVE = 0
    INACTIVE = 2
    STATUS_CHOICES = [
        (ACTIVE, 'Active'),
        (INACTIVE, 'Inactive'),
    ]
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    status = models.IntegerField (choices=STATUS_CHOICES, default=ACTIVE)

    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    

polls/forms.py
from django import forms
from .models import Question

class Question_form(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text','pub_date','status']
        widgets = {
            'pub_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

class uploadscsv_form(forms.Form):
    csv_file = forms.FileField()

polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import get_object_or_404, render , redirect
from django.urls import reverse
from django.views import generic, View
from django.utils import timezone
from .models import Choice, Question

#from .forms import Question_form
#from django.db.models import Max

import csv
from .forms import uploadscsv_form
from django.contrib import messages


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
    
def question_list(request):
    questions = Question.objects.all()
    #q = Question.pub_date
    #date=Question.pub_date()
        
    
    return render(request, "polls/table.html", {"questions": questions})
    #return HttpResponse(Question_list)


def edit_question(request, question_id):
    item = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        item.question_text = request.POST.get('question_text')
        item.pub_date = request.POST.get('pub_date')
        item.save()
        return redirect('/polls/table/') 

    return render(request, 'polls/edit.html', {'item': item})
    

def add_question(request):
    if request.method == 'POST':
        question_text = request.POST.get('question_text')
        pub_date = request.POST.get('pub_date')
        if question_text and pub_date:
            try:
                # Convert the pub_date to a datetime object
                pub_date = timezone.datetime.strptime(pub_date, '%Y-%m-%dT%H:%M')
            except ValueError:
                return render(request, 'polls/add_question.html', {'error': 'Invalid date format. Use YYYY-MM-DDTHH:MM.'})

            # Create and save the new question
            question = Question(question_text=question_text, pub_date=pub_date)
            question.save()

        return redirect('/polls/table/')  # Redirect to a page showing the list of questions

    return render(request, 'polls/add_question.html')




def delete_question(request, question_id):
    item = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        item.delete()
        return redirect('/polls/table/')  # Change 'some_view_name' to the name of the view you want to redirect to
    else:
        return render(request, 'polls/delete.html',{'item':item})

# view for uploading question from csv file 

def upload_csv(request):
    if request.method == 'POST':
        form = uploadscsv_form(request.POST, request.FILES)
        if form.is_valid():
            csv_file = request.FILES['csv_file']
            decoded_file = csv_file.read().decode('utf-8').splitlines()
            reader = csv.DictReader(decoded_file)

            for row in reader:
                question_text = row.get('question_text')
                pub_date = timezone.now()



                # Save each row as a Question object
                Question.objects.create(question_text=question_text, pub_date=pub_date)

            messages.success(request, 'CSV file uploaded and data saved successfully!')
            return redirect('/polls/table/')
    else:
        form = uploadscsv_form()
    
    return render(request, 'polls/uploadcsv.html', {'form': form})


# for download the csv file 

def download_questions_csv(request):
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="questions.csv"'

    writer = csv.writer(response)
    writer.writerow([ 'question_text', 'pub_date'])

    questions = Question.objects.all().values_list( 'question_text', 'pub_date')
    for question in questions:
        writer.writerow(question)

    return response

## Global table
from django.core.paginator import Paginator

def global_table(request):
    data = Question.objects.all().order_by('id')

    ##getting data in the pages format 
    paginator = Paginator(data, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'global/tbl_bootstrap.html', {'page_obj': page_obj})

from django.contrib.auth.decorators import login_required

@login_required
def question_status(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    if question.status == 0:
        question.status = 2
    else:
        question.status = 0
    question.save()
    return redirect('/polls/table/') 

## exporting the data using SQL query 
from django.db import connection


def export_questions(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="export_questions.csv"'

    writer = csv.writer(response)
    writer.writerow(['ID', 'Question Text', 'Publication Date'])

    # raw SQL query to fetch questions
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, question_text, pub_date FROM polls_question")
        rows = cursor.fetchall()

        for row in rows:
            writer.writerow(row)

    return response


## importing the data into the database using SQl query
from django.core.files.storage import FileSystemStorage

class ImportQuestionsView(View):
    def get(self, request):
        return render(request, 'global/import_questions.html')

    def post(self, request):
        if 'csv_file' not in request.FILES:
            return HttpResponse("No file uploaded")

        csv_file = request.FILES['csv_file']

        if not csv_file.name.endswith('.csv'):
            return HttpResponse("File is not a CSV")

        # Save the file to a temporary location
        fs = FileSystemStorage()
        filename = fs.save(csv_file.name, csv_file)
        file_path = fs.path(filename)

        with open(file_path, mode='r', encoding='utf-8') as file:
            reader = csv.reader(file)
            header = next(reader, None)  # Skip the header row

            if header is None or header != ['question_text']:
                return HttpResponse("CSV file has incorrect header format")

            with connection.cursor() as cursor:
                for row_index, row in enumerate(reader, start=1):
                    if len(row) == 1:
                        question_text = row[0]

                        pub_date = timezone.now()
                        status = 0

                        try:
                            cursor.execute(
                                """
                                INSERT INTO polls_question (question_text, pub_date, status)
                                VALUES (%s, %s, %s)
                                ON CONFLICT (id) DO UPDATE SET question_text = EXCLUDED.question_text
                                """,
                                [question_text, pub_date, status]
                            )
                        except Exception as e:
                            return HttpResponse(f"Error inserting row {row_index}: {e}")
                    else:
                        return HttpResponse(f"CSV file has incorrect format on row {row_index}")

        return  redirect('/polls/table/') 



#### geting the data and print it into table using SQL query 

def sql_table(request):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT id, question_text, pub_date, status
            FROM polls_question
            ORDER BY id
        """)
        rows = cursor.fetchall()
    # Prepare context with the data

    paginator = Paginator(rows, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj
    }
    return render(request, 'global/polls_sql_listing.html', context)



## getting the data from databse usig AJAX
from django.http import JsonResponse

def get_questions(request):
    questions = Question.objects.all().values('id', 'question_text', 'pub_date', 'status').order_by('id')
    questions_list = list(questions)
    return JsonResponse(questions_list, safe=False)
# show the data in the html 
def show_questions(request):
    return render(request, 'global/questions_list.html')


#views of API
from rest_framework import generics
from .serializers import QuestionSerializer, ChoiceSerializer

class QuestionList(generics.ListCreateAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

polls/templates/polls/add_question.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Question</title>
</head>
<body>
    <h1>Add a new question</h1>
    <form method="post">
        {% csrf_token %}
        <label for="question_text">Question:</label>
        <input type="text" id="question_text" name="question_text" required><br><br>
        <label for="pub_date">Publication Date and Time:</label>
        <input type="datetime-local" id="pub_date" name="pub_date" required><br><br>
        
        <button type="submit">Submit</button>
</body>
</html>

polls/templates/polls/delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Confirm Delete</title>
</head>
<body>
    <h1 >Are you sure you want to delete this question?</h1>
    <p><strong>Question :</strong> {{ item.question_text }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" style="background-color: red;color: white;"><strong>YES,DELETE</strong></button><br></br>
        <a href="/polls/table/">No, go back</a>
    </form>
</body>
</html>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

polls/templates/polls/download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Download Questions</title>
</head>
<body>
    <h1>Download Questions</h1>
    <a href="{% url 'download_questions_csv' %}">Download CSV</a>
</body>
</html>

polls/templates/polls/edit.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Item</title>
</head>
<body>
    <h1>Question Details</h1>
    <p><strong>Question :</strong> {{ item.question_text }}</p>
    <p><strong>Date_&_Time :</strong> {{ item.pub_date }}</p>
    <p><strong>Status :</strong> {{ item.get_status_display }}</p>
    <h2>Edit Question</h2>
    <form method="post">
        {% csrf_token %}
        <label for="Question_text">Question :</label>
        <input type="text" id="question_text" name="question_text" value="{{ item.question_text }}" required>
        <br>
        <label for="pub_date">Date_&_time:</label>
        <input type="datetime-local" id="pub_date" name="pub_date" value="{{ item.pub_date }}" required>
        <button type="submit">Save</button>
    </form>
</body>
</html>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li> 
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Polls List</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .download-button {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            color: #fff;
            background-color: lightsalmon;
            border: none;
            border-radius: 5px;
            text-decoration: none;
            text-align: center;
            cursor: pointer;
        }
        .download-button:hover {
            background-color: lightgreen;
        }
    </style>
</head>
<body>
    <h1>Questions List</h1>
    
    <strong><a href=" /polls/add/" class="download-button">ADD QUESTION</a></strong>
    <br>
    <br>
    <strong><a href="/polls/uploadcsv/" class="download-button">UPLOAD CSV FILE</a></strong>
    <br>
    <br>
    <strong><a href="/polls/download/questions/" class="download-button">DOWNLOAD CSV FILE </a></strong>
    <br>
    <br>
    <table>
        <thead>
            <tr>
                <th>Question_Id</th>
                <th>Questions</th>
                <th>Publication Date</th>
                <th>Published Time</th>
                <th>Question_Update/Edit</th>
                <th>Delete_Question</th> 
            </tr>
        </thead>
        <tbody>
            {% for q in questions%}
                <tr>
                    <td>{{q.pk}}</td>
                    <td>{{ q.question_text}}</td>
                    <td>{{ q.pub_date|date:"d-m-y" }}</td>
                    <td>{{ q.pub_date|time:"H:i:s"}}</td>
                    <td>
                        <a href="{% url 'polls:edit_question' q.pk %}">Edit</a>
                    </td>
                    <td>
                        <a href="{% url 'polls:delete_question' q.pk %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

polls/templates/polls/uploadcsv.html
<!DOCTYPE html>
<html>
<head>
    <title>CSV_UPLOAD</title>
</head>
<body>
{% block content %}
  <h2>Upload CSV File</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
{% endblock %}
</body>
</html>